language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.4.1

install:
  - "pip install $DJANGO --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "touch bluebottle/settings/local.py"

script:
  - python ./manage.py test --settings=bluebottle.settings.travis -v 2
