language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.4.3
  - DJANGO=https://github.com/django/django/archive/stable/1.5.x.zip

install:
  - "pip install $DJANGO --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "touch bluebottle/settings/local.py"
  - "touch bluebottle/settings/secrets.py"

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/stable/1.5.x.zip

script:
  - python ./manage.py test --settings=bluebottle.settings.travis -v 2
